project 'DevConToday.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevConToday' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevConToday
  pod 'Spring', :git => 'https://github.com/irekasoft/Spring.git', :branch => 'master'
  pod 'Alamofire', '~> 4.4'
  

end
